server:
  port: 8763
spring:
  zipkin:
    base-url: http://zipkin-server:9411
  sleuth:
    sampler:
      percentage: 1.0
logging:
  file: "logs/hello-client.log"
management:
  security:
    enabled: false