
foo: foo version 5
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
logging:
  file: "logs/hi-client.log"
management:
  security:
    enabled: false
