server:
  port: 3159
spring:
  zipkin:
    base-url: http://zipkin-server:9411
  sleuth:
    sampler:
      percentage: 1.0
zuul:
  routes:
    hiapi:
      path: /hiapi/**
      serviceId: feign-hi-client
    helloapi:
      path: /helloapi/**
      serviceId: hello-client
  prefix: /v1